name: Convert safetensors to GGUF

on:
  workflow_dispatch:
    inputs:
      model_url:
        description: 'URL of model.safetensors'
        required: true
      config_url:
        description: 'URL of config.json'
        required: true
      tokenizer_url:
        description: 'URL of tokenizer.model or tokenizer.json'
        required: true

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install torch transformers sentencepiece

    - name: Download HuggingFace model files
      run: |
        mkdir -p hf-model
        wget -O hf-model/model.safetensors "${{ github.event.inputs.model_url }}"
        wget -O hf-model/config.json "${{ github.event.inputs.config_url }}"
        wget -O hf-model/tokenizer.model "${{ github.event.inputs.tokenizer_url }}"

    - name: Detect tokenizer file type
      id: detect_tokenizer
      run: |
        # Detect tokenizer file type (either tokenizer.model or tokenizer.json)
        if [[ -f "hf-model/tokenizer.model" ]]; then
          echo "tokenizer_type=tokenizer.model" >> $GITHUB_ENV
        elif [[ -f "hf-model/tokenizer.json" ]]; then
          echo "tokenizer_type=tokenizer.json" >> $GITHUB_ENV
        else
          echo "No tokenizer file found!" && exit 1
        fi

    - name: Clone llama.cpp (ggml-org)
      run: |
        git clone https://github.com/ggml-org/llama.cpp.git
        cd llama.cpp
        pip install -r requirements.txt

    - name: Convert to GGUF
      run: |
        cd llama.cpp
        if [[ "$TOKENIZER_TYPE" == "tokenizer.model" ]]; then
          python3 convert_hf_to_gguf.py --outfile ../converted/model.gguf --tokenizer_path ../hf-model/tokenizer.model ../hf-model/
        elif [[ "$TOKENIZER_TYPE" == "tokenizer.json" ]]; then
          python3 convert_hf_to_gguf.py --outfile ../converted/model.gguf --tokenizer_path ../hf-model/tokenizer.json ../hf-model/
        fi

    - name: Upload GGUF model
      uses: actions/upload-artifact@v4
      with:
        name: gguf-model
        path: converted/model.gguf
